### PR TITLE
Plugin release 2.0

### PR DESCRIPTION
**Pull request by radosuav**
For QGIS 3.x

### CODE REVIEW

**Comment by radosuav** [comment]
Something went wrong with git here... Will have a look later.

**Comment by j08lue** [comment]
Hmm, loads of merge conflicts wrt. the other PR I just merged. How should we manage this? Should we put version 2 into a separate branch that we turn into `master` once QGIS 3 is properly out?

**Comment by radosuav** [comment]
Ahh yes, that's why there are conflicts :)

Yes, for now this should be kept in a new branch. Once QGIS 3 becomes more popular then QGIS 2 then we can switch the branches.

**Comment by j08lue** [comment]
Merged into branch [`qgis-3`](https://github.com/DHI-GRAS/Temporal_profile_tool/tree/qgis-3) and tagged as [`v2.0.0`](https://github.com/DHI-GRAS/Temporal_profile_tool/releases/tag/v2.0.0).

**Comment by radosuav** [comment]
Thanks!

**Pull request merged**
